#!/bin/bash

#This scripts syncs my local directories to google drive.
#The argument specifies which directory is to be synced.
#Arguments:
#schem ---> sync Schematici
#mat ---> sync Materiale

n_args=$#

if [ $n_args -ne 1 ]
then
	echo "Error. Missing argument."
	exit
fi



arg=$1

case $arg in
	schem)
		info=$(gdrive list --query "name='Schematici' and trashed=false" | grep " Schematici ")
		dirID=${info:0:33}
		gdrive sync upload /home/spino/PhD/Schematici $dirID
	;;

	mat)
		info=$(gdrive list --query "name='Materiale' and trashed=false" | grep " Materiale ")
                dirID=${info:0:33}
                gdrive sync upload /home/spino/PhD/Materiale $dirID
	;;

	lav)
		info=$(gdrive list --query "name='Lavori' and trashed=false" | grep " Lavori ")
		dirID=${info:0:33}
		gdrive sync upload /home/spino/PhD/Lavori $dirID
	;;

	*)
		echo "Error. Invalid argument."
		exit
	;;
esac

