#!/bin/bash
#This scripts syncs my local directories to google drive.
#The argument specifies which directory is to be synced.
#Arguments:
#schem ---> sync Schematici
#mat ---> sync Materiale
#etc.

n_args=$#

if [ $n_args -lt 1 ]				#check number of arguments
then
	echo "Error. Missing argument."
	exit
fi

arg=$1



case $arg in


	-h|--help)				#help option
	echo
	echo "Sync automatically a given directory in google drive."
	echo
	echo "Usage:"
	echo "dsync <option> <arguments>"
	echo
	echo "-h, --help					Print this help message and exit."
	echo "-d, --download <local_path>			Sync download by specifying short name which identifies remote and local dir."
	echo "-u, --upload <local_path>				Sync upload by specifying short name which identifies remote and local dir."
	echo "-dn, --downloadname <remote_name> <local_path>	Sync download by specifying local and remote dir separately."
	echo "-un, --uploadname <remote_name> <local_path>	Sync upload by specifying local and remote dir separately."
	echo
	;;


	-u|--upload)				#upload option
	if [ $n_args -ne 2 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi	
	dir=$2
	case $dir in

		schem)
		info=$(gdrive list --query "name='Schematici' and trashed=false" | grep " Schematici ")
		dirID=${info:0:33}
		gdrive sync upload /home/"$USER"/PhD/Schematici $dirID
		;;

		mat)
		info=$(gdrive list --query "name='Materiale' and trashed=false" | grep " Materiale ")
                dirID=${info:0:33}
                gdrive sync upload /home/"$USER"/PhD/Materiale $dirID
		;;

		csv)
		info=$(gdrive list --query "name='CSV' and trashed=false" | grep " CSV ")
		dirID=${info:0:33}
		gdrive sync upload /home/"$USER"/PhD/CSV $dirID
		;;

		lav)
		info=$(gdrive list --query "name='Lavori' and trashed=false" | grep " Lavori ")
		dirID=${info:0:33}
		gdrive sync upload /home/"$USER"/PhD/Lavori $dirID
		;;

		*)
		echo "Error. Invalid argument."
		exit
		;;
	esac
	;;


	-d|--download)					#download option
	if [ $n_args -ne 2 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi	
	dir=$2
	case $dir in

		schem)
		info=$(gdrive list --query "name='Schematici' and trashed=false" | grep " Schematici ")
		dirID=${info:0:33}
		gdrive sync download $dirID /home/"$USER"/PhD/Schematici
		;;

		mat)
		info=$(gdrive list --query "name='Materiale' and trashed=false" | grep " Materiale ")
	        dirID=${info:0:33}
                gdrive sync download $dirID /home/"$USER"/PhD/Materiale
		;;

		csv)
		info=$(gdrive list --query "name='CSV' and trashed=false" | grep " CSV ")
		dirID=${info:0:33}
		gdrive sync download $dirID /home/"$USER"/PhD/CSV
		;;

		lav)
		info=$(gdrive list --query "name='Lavori' and trashed=false" | grep " Lavori ")
		dirID=${info:0:33}
		gdrive sync download $dirID /home/"$USER"/PhD/Lavori
		;;

		*)
		echo "Error. Invalid argument."
		exit
		;;
	esac
	;;


	-un|--uploadname)					#upload name
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	remote_name=$2
	local_name=$3
	info=$(gdrive list --query "name='$remote_name' and trashed=false" | grep " $remote_name ")
	dirID=${info:0:33}
	gdrive sync upload $local_name $dirID
	;;


	-dn|--downloadname)					#downloadname
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	remote_name=$2
	local_name=$3
	info=$(gdrive list --query "name='$remote_name' and trashed=false" | grep " $remote_name " )
	dirID=${info:0:33}
	gdrive sync download $dirID $local_name
	;;


	*)
	echo
	echo "Error. Invalid argument."
	echo
	;;


esac
