#!/bin/bash

###################################################################
#
#Author: spino
#
#This script automatically clones a github remote repo
#
###################################################################


if [ $# -lt 1 ]								#Check number of arguments
then
        echo "Error. Missing argument."
        exit
fi


arg=$1


case $arg in


	-h|--help)							#help option
	echo
	echo "This script automatically clones a repository from remote"
	echo
	echo "Usage:"
	echo "gitclone <option> <argument>"
	echo
	echo "-h, --help		Print this help message and exit."
	echo "-u, --url <arg>		Clone the repo specified by <arg>"
	echo
	;;


	-u|--url)							#branch option
	if [ $# -ne 2 ]
	then
	        echo "Error. Wrong number of arguments."
	        exit
	fi
	url=$2
	file_content=(`cat /home/"$USER"/.mygitconfig`)
	token=${file_content[0]}
	expect /usr/local/bin/gitclone_and_answer.exp $url $token			#call expect scripts that uses git pull to pull a branch from remote
	;;


	*)								#default case
	echo "Error. Invalid argument."
	echo
	echo "Usage:"
	echo "gitclone <option> <argument>"
	echo
	echo "-h, --help		Print this help message and exit."
	echo "-u, --url <arg>		Clone the repo specified by <arg>"
	echo
	exit
	;;


esac
