#!/bin/bash

#################################################################
#
#Author: spino
#
#This script automatically pulls a branch from a gihub remote repo

##################################################################



if [ $# -lt 1 ]								#Check number of arguments
then
        echo "Error. Missing argument."
        exit
fi


arg=$1


case $arg in


	-h|--help)							#help option
	echo
	echo "This script automatically pulls a branch from a github remote repo."
	echo
	echo "Usage:"
	echo "gitpull <option> <argument>"
	echo
	echo "-h, --help		Print this help message and exit."
	echo "-b, --branch <arg>	Pull the <arg> branch."
	echo
	;;


	-b|--branch)							#branch option
	if [ $# -ne 2 ]
	then
	        echo "Error. Wrong number of arguments."
	        exit
	fi
	branch_name=$2
	file_content=(`cat /home/"$USER"/.mygitconfig`)
	token=${file_content[0]}
	expect /usr/local/bin/gitpull_and_answer.exp $branch_name $token		#call expect scripts that uses git pull to pull a branch from remote
	;;


	*)								#default case
	echo "Error. Invalid argument."
	echo
	echo "Usage:"
	echo "gitpull <option> <argument>"
	echo
	echo "-h, --help		Print this help message and exit."
	echo "-b, --branch <arg>	Pull the <arg> branch."
	echo
	exit
	;;


esac
