#!/bin/bash


if [ $# -lt 1 ]
then
        echo "Error. Missing argument."
        exit
fi


arg=$1

case $arg in
	
	"-h")
	echo "This script automatically pushes a local branch into a remote repo."
	echo "The repo must be previuosly selected by using git add origin *link*." 
	;;

	"-b")
	if [ $# -ne 2 ]
	then
	        echo "Error. Wrong number of arguments."
	        exit
	fi
	branch_name=$2
	file=`cat /usr/local/bin/token.txt`
	token=${file:0:43}
	expect /usr/local/bin/gitpush_and_answer.exp $branch_name $token
	;;
	
	*)
	echo "Error. Invalid argument."
	exit
	;;

esac
