#!/bin/bash


n_args=$#


if [ $n_args -lt 1 ]
then
        echo "Error. Missing argument."
        exit
fi



arg=$1



case $arg in


	-h|--help)
	echo
	echo "Sync automatically a given directory in google drive."
	echo
	echo "-h, --help 						Print this help message and exit."
	echo "-d, --download <remote_name>				Download <remote_name>."
	echo "-u, --upload <local_name> <remote_folder>			Upload <local_name> into <remote_folder>."
	echo "-fu, --folderupdate <local_folder> <remote_folder>	Update the content of <remote_folder> by uploading/updating from <local_folder>."
	echo "-fd, --folderdownload <remote_folder> <local_folder>	Download the content of <remote_folder> into <local_folder>. Files with the same name are not downloaded."
	echo "-fo, --folderoverwrite <remote_folder> <local_folder>	Download the content of <remote_folder> into <local_folder> and overwrite files with the same names."
	echo
	;;


	-d|--download)
	if [ $n_args -ne 2 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	file_name=$2
	gdrive download query "name='$file_name'"	
	;;


	-u|--upload)
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	file_name=$2
	remote_dir=$3
	info=$(gdrive list --query "name='$remote_dir' and trashed=false" | grep " $remote_dir ")
	remote_dir_ID=${info:0:33}
	gdrive upload -p $remote_dir_ID $file_name	
	;;


	-fu|--folderupdate)
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	;;


	-fd|folderdownload)
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	;;


	-fo|--folderoverwrite)
	if [ $n_args -ne 3 ]
	then
		echo "Error. Wrong number of arguments."
		exit
	fi
	;;


esac
