#!/bin/bash

if [ $# -lt 1 ]
then
	echo "Error. Wrong number of arguments."
	exit
fi


arg=$1

case $arg in

	-h|--help)
	echo
	echo "This script updates my bash scripts."
	echo
	echo "-h --help Print this help message and exit."
	echo "-a --update-all Update all the scripts."
	echo "-s --script <argument> Update only <argument>."
	echo
	;;

	-a|--update-all)
	scripts=`ls /home/spino/MyCode/Scripts`
	sudo install $scripts /usr/local/bin && echo "The scripts were successfully updated." || echo "Update failed."
	;;

	-s|--script)
	if [ $# -ne 2 ]
	then
		echo "Error. Missing argument."
	fi
	script_name=$2
	sudo install /home/spino/MyCode/Scripts/"$script_name" /usr/local/bin && echo "$script_name was successfully updated." || echo "Update failed."
	;;

esac
