#!/bin/bash

if [ $# -lt 1 ]											#check number of arguments
then
	echo "Error. Wrong number of arguments."
	exit
fi


arg=$1



case $arg in


	-h|--help)										#help option
	echo
	echo "This script updates my bash scripts."
	echo
	echo "Usage:"
	echo "scrupd <option> <argument>"
	echo
	echo "-h --help 			Print this help message and exit."
	echo "-a --update-all 			Update all the scripts."
	echo "-s --script <argument> 		Update only <argument>."
	echo
	;;


	-a|--update-all)									#update all option
	scripts=`ls /home/spino/MyCode/Bash`
	cd /home/spino/MyCode/Bash
	sudo install $scripts /usr/local/bin && echo "The scripts were successfully updated." || echo "Update failed."
	;;


	-s|--script)										#update script option
	if [ $# -ne 2 ]
	then
		echo "Error. Missing argument."
	fi
	script_name=$2
	sudo install /home/spino/MyCode/Bash/"$script_name" /usr/local/bin && echo "$script_name was successfully updated." || echo "Update failed."
	;;


	*)
	echo "Error. Invalid option."
	echo
	echo "Usage:"
	echo "scrupd <option> <argument>"
	echo
	echo "-h --help 			Print this help message and exit."
	echo "-a --update-all 			Update all the scripts."
	echo "-s --script <argument> 		Update only <argument>."
	echo
	;;


esac
